name: Build, Push to ECR, and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      # 2. 날짜와 시간 태그 생성
      - name: Generate Date-Time Tag
        id: date-time
        run: |
          echo "IMAGE_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      # 3. 소나큐브 분석
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # 소나큐브 토큰
        run: |
          # SonarScanner 설치
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip -d $HOME/sonar-scanner
          export PATH="$HOME/sonar-scanner/sonar-scanner-5.0.1.3006-linux/bin:$PATH"
          
          # 소나큐브 분석 실행
          sonar-scanner \
            -Dsonar.projectKey=olivecinema_back \
            -Dsonar.host.url=http://54.180.236.23:9000 \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.sources=. \
            -Dsonar.java.binaries=build/classes/java/main \

      # 4. AWS 자격증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 5. Amazon ECR 로그인
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/hjh/backend:${{ env.IMAGE_TAG }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # 7. ArgoCD 브랜치로 전환
      - name: Checkout ArgoCD Branch
        uses: actions/checkout@v3
        with:
          ref: argocd

      # 8. Kubernetes 매니페스트 업데이트
      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: .*|image: 051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/hjh/backend:${{ env.IMAGE_TAG }}|" k8s/deployment.yaml

      # 9. 변경사항 커밋 및 푸시
      - name: Commit and Push Changes to ArgoCD Branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update image tag to ${{ env.IMAGE_TAG }}"
          branch: argocd
